import React, { useState } from 'react';

interface ModeSelectionModalProps {
  isOpen: boolean;
  onClose: () => void;
  currentMode: 'ai' | 'db';
  onModeChange: (mode: 'ai' | 'db') => void;
}

export const ModeSelectionModal: React.FC<ModeSelectionModalProps> = ({
  isOpen,
  onClose,
  currentMode,
  onModeChange,
}) => {
  const [selectedMode, setSelectedMode] = useState<'ai' | 'db'>(currentMode);

  if (!isOpen) return null;

  const handleConfirm = () => {
    onModeChange(selectedMode);
    onClose();
  };

  return (
    <div className="fixed inset-0 bg-slate-900/90 backdrop-blur-sm z-50 flex items-center justify-center p-4 animate-fade-in">
      <div className="w-full max-w-md mx-auto bg-slate-800 rounded-2xl border border-slate-700 shadow-2xl transform transition-all duration-300 animate-slide-up">
        {/* Header */}
        <div className="p-6 border-b border-slate-700">
          <h2 className="text-2xl font-bold text-white text-center">Select Question Mode</h2>
          <p className="text-slate-400 text-center text-sm mt-2">Choose how you want to receive coding challenges</p>
        </div>

        {/* Content */}
        <div className="p-6 space-y-4">
          {/* AI Mode Option */}
          <div
            onClick={() => setSelectedMode('ai')}
            className={`p-4 rounded-lg border-2 cursor-pointer transition-all duration-200 ${
              selectedMode === 'ai'
                ? 'bg-sky-500/20 border-sky-500 shadow-lg'
                : 'bg-slate-700/50 border-slate-600 hover:bg-slate-700 hover:border-slate-500'
            }`}
          >
            <div className="flex items-start gap-3">
              <div className={`w-5 h-5 rounded-full border-2 flex-shrink-0 mt-0.5 flex items-center justify-center ${
                selectedMode === 'ai' ? 'border-sky-400 bg-sky-500' : 'border-slate-500'
              }`}>
                {selectedMode === 'ai' && (
                  <div className="w-2.5 h-2.5 rounded-full bg-white"></div>
                )}
              </div>
              <div className="flex-1">
                <h3 className={`font-semibold mb-1 ${selectedMode === 'ai' ? 'text-white' : 'text-slate-300'}`}>
                  AI Mode (Gemini API)
                </h3>
                <p className="text-sm text-slate-400 mb-2">Fresh questions generated by AI</p>
                <ul className="text-xs text-slate-400 space-y-1">
                  <li>• Unlimited variety</li>
                  <li>• Tailored to your preferences</li>
                  <li>• Always unique challenges</li>
                </ul>
              </div>
            </div>
          </div>

          {/* DB Mode Option */}
          <div
            onClick={() => setSelectedMode('db')}
            className={`p-4 rounded-lg border-2 cursor-pointer transition-all duration-200 ${
              selectedMode === 'db'
                ? 'bg-sky-500/20 border-sky-500 shadow-lg'
                : 'bg-slate-700/50 border-slate-600 hover:bg-slate-700 hover:border-slate-500'
            }`}
          >
            <div className="flex items-start gap-3">
              <div className={`w-5 h-5 rounded-full border-2 flex-shrink-0 mt-0.5 flex items-center justify-center ${
                selectedMode === 'db' ? 'border-sky-400 bg-sky-500' : 'border-slate-500'
              }`}>
                {selectedMode === 'db' && (
                  <div className="w-2.5 h-2.5 rounded-full bg-white"></div>
                )}
              </div>
              <div className="flex-1">
                <h3 className={`font-semibold mb-1 ${selectedMode === 'db' ? 'text-white' : 'text-slate-300'}`}>
                  DB Mode (Database only)
                </h3>
                <p className="text-sm text-slate-400 mb-2">Questions from our database</p>
                <ul className="text-xs text-slate-400 space-y-1">
                  <li>• No API calls</li>
                  <li>• Filtered by your settings</li>
                  <li>• No repetition tracking</li>
                </ul>
              </div>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="p-4 bg-slate-900/50 border-t border-slate-700 rounded-b-2xl flex justify-end gap-3">
          <button
            onClick={onClose}
            className="px-5 py-2.5 text-sm font-semibold text-slate-300 hover:bg-slate-700 rounded-md transition-colors"
          >
            Cancel
          </button>
          <button
            onClick={handleConfirm}
            className="px-5 py-2.5 text-sm font-semibold text-white bg-sky-600 hover:bg-sky-500 rounded-md transition-colors shadow-sm"
          >
            Confirm
          </button>
        </div>
      </div>

      <style>{`
        @keyframes fade-in {
          from { opacity: 0; }
          to { opacity: 1; }
        }
        @keyframes slide-up {
          from { transform: translateY(20px); opacity: 0; }
          to { transform: translateY(0); opacity: 1; }
        }
        .animate-fade-in { animation: fade-in 0.3s ease-out forwards; }
        .animate-slide-up { animation: slide-up 0.4s ease-out forwards; }
      `}</style>
    </div>
  );
};
